FROM golang:1.21.1

WORKDIR /america

COPY go.mod go.sum ./

RUN go mod download

COPY america/parametros_de_inicio.txt ./
COPY america/main.go ./

RUN go build -o america_bin .

ENTRYPOINT [ "/america/america_bin" ]