FROM golang:1.21.1

WORKDIR /oceania

COPY go.mod go.sum ./

RUN go mod download

COPY oceania/parametros_de_inicio.txt ./oceania/
COPY oceania/main.go ./

RUN go build -o oceania_bin .

ENTRYPOINT [ "/oceania/oceania_bin" ]