FROM golang:1.21.1

WORKDIR /central

COPY go.mod go.sum ./

RUN go mod download

COPY central/main.go ./

# RUN go get github.com/GonzaloDiaz300/LAB/proto

RUN go build -o central_bin .

ENTRYPOINT [ "/central/central_bin" ]