FROM golang:1.21.1

WORKDIR /oceania

COPY go.mod go.sum ./

RUN go mod download

COPY oceania/main.go ./

# RUN go get github.com/GonzaloDiaz300/LAB/proto

RUN go build -o oceania_bin .

ENTRYPOINT [ "/oceania/oceania_bin" ]