FROM golang:1.21.1

WORKDIR /asia

COPY go.mod go.sum ./

RUN go mod download

COPY asia/main.go ./

# RUN go get github.com/GonzaloDiaz300/LAB/proto

RUN go build -o asia_bin .

ENTRYPOINT [ "/asia/asia_bin" ]