FROM golang:1.21.1

WORKDIR /central

COPY go.mod go.sum ./

RUN go mod download

COPY central/parametros_de_inicio.txt ./
COPY central/main.go ./

RUN go build -o central_bin .

ENTRYPOINT [ "/central/central_bin" ]