// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: america/proto/america.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitud int32 `protobuf:"varint,1,opt,name=solicitud,proto3" json:"solicitud,omitempty"`
}

func (x *NotiReq) Reset() {
	*x = NotiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_america_proto_america_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotiReq) ProtoMessage() {}

func (x *NotiReq) ProtoReflect() protoreflect.Message {
	mi := &file_america_proto_america_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotiReq.ProtoReflect.Descriptor instead.
func (*NotiReq) Descriptor() ([]byte, []int) {
	return file_america_proto_america_proto_rawDescGZIP(), []int{0}
}

func (x *NotiReq) GetSolicitud() int32 {
	if x != nil {
		return x.Solicitud
	}
	return 0
}

type NotiResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta int32 `protobuf:"varint,1,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *NotiResp) Reset() {
	*x = NotiResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_america_proto_america_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotiResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotiResp) ProtoMessage() {}

func (x *NotiResp) ProtoReflect() protoreflect.Message {
	mi := &file_america_proto_america_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotiResp.ProtoReflect.Descriptor instead.
func (*NotiResp) Descriptor() ([]byte, []int) {
	return file_america_proto_america_proto_rawDescGZIP(), []int{1}
}

func (x *NotiResp) GetRespuesta() int32 {
	if x != nil {
		return x.Respuesta
	}
	return 0
}

type InscritosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitud_2 int32 `protobuf:"varint,1,opt,name=solicitud_2,json=solicitud2,proto3" json:"solicitud_2,omitempty"`
}

func (x *InscritosReq) Reset() {
	*x = InscritosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_america_proto_america_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InscritosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscritosReq) ProtoMessage() {}

func (x *InscritosReq) ProtoReflect() protoreflect.Message {
	mi := &file_america_proto_america_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscritosReq.ProtoReflect.Descriptor instead.
func (*InscritosReq) Descriptor() ([]byte, []int) {
	return file_america_proto_america_proto_rawDescGZIP(), []int{2}
}

func (x *InscritosReq) GetSolicitud_2() int32 {
	if x != nil {
		return x.Solicitud_2
	}
	return 0
}

type InscritosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta_2 int32 `protobuf:"varint,1,opt,name=respuesta_2,json=respuesta2,proto3" json:"respuesta_2,omitempty"`
}

func (x *InscritosResp) Reset() {
	*x = InscritosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_america_proto_america_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InscritosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscritosResp) ProtoMessage() {}

func (x *InscritosResp) ProtoReflect() protoreflect.Message {
	mi := &file_america_proto_america_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscritosResp.ProtoReflect.Descriptor instead.
func (*InscritosResp) Descriptor() ([]byte, []int) {
	return file_america_proto_america_proto_rawDescGZIP(), []int{3}
}

func (x *InscritosResp) GetRespuesta_2() int32 {
	if x != nil {
		return x.Respuesta_2
	}
	return 0
}

var File_america_proto_america_proto protoreflect.FileDescriptor

var file_america_proto_america_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x27, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x69, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x22, 0x28, 0x0a, 0x08,
	0x4e, 0x6f, 0x74, 0x69, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x75, 0x64, 0x5f, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x32, 0x22, 0x30, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x63, 0x72,
	0x69, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x5f, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72,
	0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x32, 0x32, 0x70, 0x0a, 0x0c, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x09, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x72, 0x12, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x74,
	0x69, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x69, 0x72, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e,
	0x73, 0x63, 0x72, 0x69, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x6e, 0x7a, 0x61, 0x6c,
	0x6f, 0x44, 0x69, 0x61, 0x7a, 0x33, 0x30, 0x30, 0x2f, 0x4c, 0x41, 0x42, 0x2f, 0x61, 0x6d, 0x65,
	0x72, 0x69, 0x63, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_america_proto_america_proto_rawDescOnce sync.Once
	file_america_proto_america_proto_rawDescData = file_america_proto_america_proto_rawDesc
)

func file_america_proto_america_proto_rawDescGZIP() []byte {
	file_america_proto_america_proto_rawDescOnce.Do(func() {
		file_america_proto_america_proto_rawDescData = protoimpl.X.CompressGZIP(file_america_proto_america_proto_rawDescData)
	})
	return file_america_proto_america_proto_rawDescData
}

var file_america_proto_america_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_america_proto_america_proto_goTypes = []interface{}{
	(*NotiReq)(nil),       // 0: grpc.NotiReq
	(*NotiResp)(nil),      // 1: grpc.NotiResp
	(*InscritosReq)(nil),  // 2: grpc.InscritosReq
	(*InscritosResp)(nil), // 3: grpc.InscritosResp
}
var file_america_proto_america_proto_depIdxs = []int32{
	0, // 0: grpc.Notificacion.Notificar:input_type -> grpc.NotiReq
	2, // 1: grpc.Notificacion.Inscribir:input_type -> grpc.InscritosReq
	1, // 2: grpc.Notificacion.Notificar:output_type -> grpc.NotiResp
	3, // 3: grpc.Notificacion.Inscribir:output_type -> grpc.InscritosResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_america_proto_america_proto_init() }
func file_america_proto_america_proto_init() {
	if File_america_proto_america_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_america_proto_america_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_america_proto_america_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotiResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_america_proto_america_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InscritosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_america_proto_america_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InscritosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_america_proto_america_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_america_proto_america_proto_goTypes,
		DependencyIndexes: file_america_proto_america_proto_depIdxs,
		MessageInfos:      file_america_proto_america_proto_msgTypes,
	}.Build()
	File_america_proto_america_proto = out.File
	file_america_proto_america_proto_rawDesc = nil
	file_america_proto_america_proto_goTypes = nil
	file_america_proto_america_proto_depIdxs = nil
}
